public enum Endpoint {
    GET_TASKS,
    GET_TASK,
    GET_SUBTASKS,
    GET_SUBTASK,
    GET_EPICS,
    GET_EPIC,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED,
    DELETE_TASK,
    DELETE_SUBTASK,
    DELETE_EPIC,
    POST_TASKS,
    POST_SUBTASKS,
    POST_EPICS,
    UNKNOWN
}
